services:

    order-db:
          image: mongo
          container_name: order-mongo
          restart: always
          environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
          ports:
            - "27017:27017"
          networks:
            - ms_net

    account-db:
          image: postgres:16-alpine
          container_name: accounts-postgres
          environment:
            - POSTGRES_DB=account
            - POSTGRES_USER=account
            - POSTGRES_PASSWORD=account
          ports:
            - "5432:5432"
          volumes:
            - account_data:/var/lib/postgresql/data
          healthcheck:
            test: ["CMD-SHELL", "pg_isready -U account -d account"]
            interval: 10s
            timeout: 5s
            retries: 5
          networks:
            - ms_net


#    product-db:
#            image: postgres:16-alpine
#            container_name: product-postgres
#            environment:
#              - POSTGRES_DB=product
#              - POSTGRES_USER=product
#              - POSTGRES_PASSWORD=product
#            ports:
#              - "5433:5432"
#            volumes:
#              - product_data:/var/lib/postgresql/data
#            healthcheck:
#              test: ["CMD-SHELL", "pg_isready -U product -d product"]
#              interval: 10s
#              timeout: 5s
#              retries: 5
#            networks:
#              - ms_net

#    payment-db:
#            image: postgres:16-alpine
#            container_name: payment-postgres
#            environment:
#              - POSTGRES_DB=payment
#              - POSTGRES_USER=payment
#              - POSTGRES_PASSWORD=payment
#            ports:
#              - "5434:5432"
#            volumes:
#              - payment_data:/var/lib/postgresql/data
#            healthcheck:
#              test: [ "CMD-SHELL", "pg_isready -U payment -d payment" ]
#              interval: 10s
#              timeout: 5s
#              retries: 5
#            networks:
#              - ms_net

#    inventory-db:
#            image: postgres:16-alpine
#            container_name: invetory-postgres
#            environment:
#              - POSTGRES_DB=inventory
#              - POSTGRES_USER=inventory
#              - POSTGRES_PASSWORD=inventory
#            ports:
#              - "5435:5432"
#            volumes:
#              - inventory_data:/var/lib/postgresql/data
#            healthcheck:
#              test: [ "CMD-SHELL", "pg_isready -U inventory -d inventory" ]
#              interval: 10s
#              timeout: 5s
#              retries: 5
#            networks:
#              - ms_net


    kafka:
            image: obsidiandynamics/kafka
            container_name: kafka-server
            restart: "no"
            networks:
              - ms_net
            ports:
              - "2181:2181"
              - "9092:9092"
            environment:
              KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
              KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
              KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
              KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
              KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
              KAFKA_RESTART_ATTEMPTS: "10"
              KAFKA_RESTART_DELAY: "5"
              ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"

    schema-registry:
      image: confluentinc/cp-schema-registry
      networks:
        - ms_net
      ports:
        - "8079:8081"
      environment:
        SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:29092
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
      depends_on:
        - kafka

    kafka-ui:
      container_name: kafka-ui
      image: provectuslabs/kafka-ui:latest
      networks:
        - ms_net
      ports:
        - "8080:8080"
      environment:
        KAFKA_CLUSTERS_0_NAME: local
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
        KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      depends_on:
        - kafka
        - schema-registry

#    accounts-api:
#            build:
#              context: ./accounts-api
#              dockerfile: Dockerfile
#            container_name: accounts-api
#            restart: on-failure
#            networks:
#              - ms_net
#            ports:
#              - "8081:8081"
#            environment:
#              SPRING_DATASOURCE_URL: jdbc:postgresql://accounts-postgres:5432/account
#              SPRING_DATASOURCE_USERNAME: account
#              SPRING_DATASOURCE_PASSWORD: account
#            depends_on:
#              account-db:
#                condition: service_healthy
#            healthcheck:
#              test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
#              interval: 30s
#              timeout: 10s
#              retries: 3
#              start_period: 40s
#
#    order-service:
#            build:
#              context: ./order-service_ms
#              dockerfile: Dockerfile
#            container_name: order-service
#            restart: on-failure
#            networks:
#              - ms_net
#            ports:
#              - "8083:8083"
#            environment:
#              KAFKA_BROKER: kafka:29092
#              MONGO_DB_URI: mongodb://admin:admin@order-mongo:27017
#            depends_on:
#              kafka:
#                condition: service_started
#              order-db:
#                condition: service_started
#            healthcheck:
#              test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
#              interval: 30s
#              timeout: 10s
#              retries: 3
#              start_period: 40s
#
#    product-validation:
#            build:
#              context: ./product_validation-service_ms
#              dockerfile: Dockerfile
#            container_name: product-validation
#            restart: on-failure
#            networks:
#              - ms_net
#            ports:
#              - "8082:8082"
#            environment:
#              SPRING_DATASOURCE_URL: jdbc:postgresql://product-postgres:5432/product
#              SPRING_DATASOURCE_USERNAME: product
#              SPRING_DATASOURCE_PASSWORD: product
#              SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
#            depends_on:
#              product-db:
#                condition: service_healthy
#              kafka:
#                condition: service_started
#            healthcheck:
#              test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
#              interval: 30s
#              timeout: 10s
#              retries: 3
#              start_period: 40s
#
#    orchestrator-service:
#            build:
#              context: ./orchestrator-service_ms
#              dockerfile: Dockerfile
#            container_name: orchestrator-service
#            restart: on-failure
#            networks:
#              - ms_net
#            ports:
#              - "8090:8090"
#            environment:
#              SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
#            depends_on:
#              kafka:
#                condition: service_started
#            healthcheck:
#              test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
#              interval: 30s
#              timeout: 10s
#              retries: 3
#              start_period: 40s


volumes:
  account_data:
  product_data:
  payment_data:
  inventory_data:

networks:
  ms_net:
    driver: bridge
