
spring:
  application:
    name: order-service

  kafka:
      bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
      topic:
          start-saga: start-saga
          notify-end: notify-end
      consumer:
        group-id: order-group
        auto-offset-reset: latest

  mongodb:
      uri: ${MONGO_DB_URI:mongodb://admin:admin@localhost:27017}
      database: admin

logging:
  level:
    org:
      apache:
        kafka: OFF
server:
  port: 8083
