spring:
  application:
    name: orchestrator
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest

server:
  port: 8090

logging:
  level:
    org:
      apache:
        kafka: OFF
